In [100]:
import numpy as np
import pandas as pd
import matplotlib as mlt

In [101]:
from google.colab import files
zmo = files.upload()

Saving zomato_dataset.csv to zomato_dataset (2).csv

In [147]:
zmo = pd.read_csv('zomato_dataset (2).csv')

In [148]:
zmo

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NaN,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,NaN,0,525.0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,NaN,0,525.0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,NaN,0,525.0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,NaN,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [149]:
# Exploratory data analysis EDA
zmo.shape

(123657, 12)

In [150]:
# view creation
zmo.columns

Index(['Restaurant Name', 'Dining Rating', 'Delivery Rating', 'Dining Votes',
       'Delivery Votes', 'Cuisine ', 'Place Name', 'City', 'Item Name',
       'Best Seller', 'Votes', 'Prices'],
      dtype='object')

In [151]:
zmo.head(1000)

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NaN,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,Burger King,4.1,4.1,253,0,Fast Food,The Next Galleria Mall,Hyderabad,Boneless Wings Large,NaN,8,249.0
996,Burger King,4.1,4.1,253,0,Fast Food,The Next Galleria Mall,Hyderabad,Chicken Wings Grilled - Ten Pcs,NaN,0,349.0
997,Burger King,4.1,4.1,253,0,Fast Food,The Next Galleria Mall,Hyderabad,Chicken Wings - five Pcs Fried + Five Pcs Grilled,NaN,21,349.0
998,Burger King,4.1,4.1,253,0,Fast Food,The Next Galleria Mall,Hyderabad,Chicken Wings Fried - Ten Pieces,NaN,17,349.0
999,Burger King,4.1,4.1,253,0,Fast Food,The Next Galleria Mall,Hyderabad,Chicken Wings Fried - Fifteen Pieces,NaN,0,529.0

In [152]:
zmo.tail(1000)

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
122657,Burger Singh - Big Punjabi Burgers,NaN,NaN,0,0,Pizza,Tatibandh,Raipur,Dilli-6 Fries (Large),NaN,0,119.0
122658,Burger Singh - Big Punjabi Burgers,NaN,NaN,0,0,Pizza,Tatibandh,Raipur,Hot Shock Fries (Regular),SPICY,0,80.0
122659,Burger Singh - Big Punjabi Burgers,NaN,NaN,0,0,Pizza,Tatibandh,Raipur,Hot Shock Fries (Large),SPICY,0,119.0
122660,Burger Singh - Big Punjabi Burgers,NaN,NaN,0,0,Pizza,Tatibandh,Raipur,Classic Salted Fries (Regular),NaN,0,80.0
122661,Burger Singh - Big Punjabi Burgers,NaN,NaN,0,0,Pizza,Tatibandh,Raipur,Classic Salted Fries (Large),NaN,0,119.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,NaN,0,525.0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,NaN,0,525.0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,NaN,0,525.0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,NaN,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [153]:
zmo.info()------# Technical enquiry

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123657 entries, 0 to 123656
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Restaurant Name  123657 non-null  object
 1   Dining Rating    91421 non-null   float64
 2   Delivery Rating  122377 non-null  float64
 3   Dining Votes     123657 non-null  int64
 4   Delivery Votes   123657 non-null  int64
 5   Cuisine          123657 non-null  object
 6   Place Name       123657 non-null  object
 7   City             123657 non-null  object
 8   Item Name        123657 non-null  object
 9   Best Seller      27942 non-null   object
 10  Votes            123657 non-null  int64
 11  Prices           123657 non-null  float64
dtypes: float64(3), int64(3), object(6)
memory usage: 11.3+ MB

In [154]:
zmo.describe()-------# statistical enquiry

,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Votes,Prices
count,91421.000000,122377.000000,123657.000000,123657.000000,123657.000000,123657.000000
mean,3.822264,3.963184,152.729858,115.763725,24.666772,241.378399
std,0.408693,0.245900,232.214061,243.970828,125.236009,192.830713
min,2.500000,2.500000,0.000000,0.000000,0.000000,0.950000
25%,3.600000,3.800000,0.000000,0.000000,0.000000,130.000000
50%,3.900000,4.000000,30.000000,0.000000,0.000000,208.570000
75%,4.100000,4.100000,217.000000,23.000000,15.000000,299.000000
max,4.800000,4.600000,997.000000,983.000000,9750.000000,12024.000000

In [155]:
zmo.isnull().sum()

Restaurant Name        0
Dining Rating      32236
Delivery Rating     1280
Dining Votes           0
Delivery Votes         0
Cuisine                0
Place Name             0
City                   0
Item Name              0
Best Seller        95715
Votes                  0
Prices                 0
dtype: int64

In [156]:
zmo.isnull().sum()

Restaurant Name        0
Dining Rating      32236
Delivery Rating     1280
Dining Votes           0
Delivery Votes         0
Cuisine                0
Place Name             0
City                   0
Item Name              0
Best Seller        95715
Votes                  0
Prices                 0
dtype: int64

In [157]:
zmo.isnull().mean()

Restaurant Name    0.000000
Dining Rating      0.260689
Delivery Rating    0.010351
Dining Votes       0.000000
Delivery Votes     0.000000
Cuisine            0.000000
Place Name         0.000000
City               0.000000
Item Name          0.000000
Best Seller        0.774036
Votes              0.000000
Prices             0.000000
dtype: float64

In [158]:
# data cleaning
zmo1 = zmo["Dining Rating"].dropna()

In [159]:
zmo1

0         3.9
1         3.9
2         3.9
3         3.9
4         3.9
         ...
123652    3.9
123653    3.9
123654    3.9
123655    3.9
123656    3.9
Name: Dining Rating, Length: 91421, dtype: float64

In [160]:
zmo2 =zmo.iloc[:,[1]]

In [161]:
zmo2

        Dining Rating
0                 3.9
1                 3.9
2                 3.9
3                 3.9
4                 3.9
...               ...
123652            3.9
123653            3.9
123654            3.9
123655            3.9
123656            3.9

[123657 rows x 1 columns]

In [162]:
subset = zmo.iloc[0:123657,0:11]

In [163]:
subset

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NaN,39
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31
...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,NaN,0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,NaN,0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,NaN,0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,NaN,0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0

In [164]:
subset = zmo.fillna(zmo.mode().iloc[0])

In [165]:
subset

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,BESTSELLER,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,BESTSELLER,0,525.0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,BESTSELLER,0,525.0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,BESTSELLER,0,525.0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,BESTSELLER,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [166]:
subset.isnull().sum()

Restaurant Name    0
Dining Rating      0
Delivery Rating    0
Dining Votes       0
Delivery Votes     0
Cuisine            0
Place Name         0
City               0
Item Name          0
Best Seller        0
Votes              0
Prices             0
dtype: int64

In [167]:
subset4 = subset.copy()

In [168]:
subset4

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,BESTSELLER,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,BESTSELLER,0,525.0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,BESTSELLER,0,525.0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,BESTSELLER,0,525.0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,BESTSELLER,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [169]:
x = subset4.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,11]]

In [170]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,BESTSELLER,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,BESTSELLER,0,525.0
123653,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,BESTSELLER,0,525.0
123654,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,BESTSELLER,0,525.0
123655,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,BESTSELLER,0,525.0
123656,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [171]:
x['Restaurant Name'].unique()

array(['Doner King', 'Taco Bell', 'BrownBear', 'Crystal Restaurant & Bar',
       'Siddique Kabab Centre', 'Shah Ghouse Special Shawarma',
       'Taj Mahal - Taj Mahal Hotel', 'Burger King', 'Papadams Blue',
       'Ovenstory Pizza', 'Italian Pizzeria', 'Al Rabea Mandi House',
       'Govind Dosa', 'Universal Al Mataam Mandi Kebab & Biryani',
       'The Thickshake Factory', 'Platform 65', 'Food Track',
       'The Burger Club', 'Acme Candy Food', 'MS Bakery & Sweets',
       'New Grand Restaurant & Bakery', 'Al - Hamoor Arabian Restaurant',
       "McDonald's", 'Capital Multi Cuisine Restaurant',
       'Mayur Pan House', 'Yashwanth Pizza Den', 'Hotel Nayaab',
       'Red Bucket Biryani', 'Hotel Shadab', 'Mughal Restaurant',
       'UBQ by Barbeque Nation', 'Santosh Dhaba', 'Tipsy Topsy Bakery',
       'Shah Ghouse Hotel & Restaurant', "La Pino'z Pizza", 'Istanbul',
       'Iqbal Cafe', 'Barbeque Nation',
       'Kwality Wall\x92s Frozen Dessert and Ice Cream Shop',
       'Akbar Fast Food', 'The Belgian Waffle Co.', 'Nimrah Restaurant',
       'Marhaba Shawarma & Wraps', 'Mandi Town', 'Paradise Biryani',
       'Redaan Restaurant', 'Sip & Bite', 'Peshawar',
       'Al Farooj Sonu Kabab', 'Lucky Restaurant',
       'Zomoz - The Momo Company', 'Ambika Foods', 'Swagth Hotel',
       'Onesta', 'Subhan Bakery', 'MRCB', 'Shree Santosh Family Dhaba',
       'Fancy Ice Cream', 'Blue Sea Restaurant', 'Mataam Al Yamani',
       'Mohammedia Shawarma', "Wendy's Burgers", 'The Exotic Shawarma',
       'Cafe Niloufer', '4M Biryani House', 'Grand Bawarchi Restaurant',
       'California Burrito', 'Sarvi Restaurant', 'Grand Hotel',
       "Barrack's Grill", 'Pista House Bakery', 'KS Bakers',
       'Pista House', 'Captain Kunafa', "Zafar's Fine Dine",
       'Amfah Hotel', 'Al Akbar Fast Food Corner',
       "Chotu's The Food People", 'Subway', 'CakeZone',
       'Faasos - Wraps & Rolls', 'Down Town Restaurant & Cafeteria',
       'Hotel Swagath Grand', 'Arabian Central', 'Arabian Food Court',
       'Louis Burger', 'WOW! Momo', 'Art Of Biryani',
       'New King Safina Hotel', 'MS Bakery', 'A Balaji Santosh Dhaba',
       'Kritunga', 'Dine Hill', 'Zaffran Mataam Alarabi', 'Bawarchi',
       'Balaji Santosh Family Dhaba', 'Swiss Castle', 'The Tea Planet',
       'Lucky Multicuisine Restaurant', 'Express By ABs',
       'Late Night Biryani', 'Karachi Bakery', 'Coffee Cream', 'Mehfil',
       'Surabhi Grand', 'MS Mandi & Shawarma',
       'Gelatica Gelato - Ice Cream', 'Scoops Ice Cream',
       'Spice 9 Restaurant', 'Al Rabea Al Arabi Cafeteria',
       'Hotel Rumaan', 'Pista House - Premium Lounge', 'Lassi Shop',
       'Nazeer Juice Center', 'Sherton Restaurant',
       'Hotel Shubham Prestige', 'Cream Stone Ice Cream',
       "Tibb's Frankie - Serving Rolls Since 1969",
       "Leon's Burgers & Wings", 'New Santosh Dhaba', 'NIC Ice Creams',
       'Blue Sea Tea & Bakery', 'Indira Darshini',
       'Cafe 555 & Aqeeq Restaurant', 'Pizza Hut', 'Shadaan Restaurant',
       'Exotica', 'The Wrap House', 'Natural Ice Cream', 'Oye Kiddan',
       'Maiz Mexican Kitchen', 'BOX8 - Desi Meals', 'Hot N Spicy',
       'Charcoal Eats - Biryani & Beyond', 'Biryani By Kilo',
       "Smokin' Joe's", '99 Pancakes', 'Cheelizza - India Ka Pizza',
       '1441 Pizzeria', 'Starboy Pizza & Shakes', 'Shivsu Pizza',
       'Dum Safar Biryani', 'Chaitanya', 'The Good Bowl', 'SP Burger',
       'PizzaExpress', 'The Momo Factory', 'Dadar Social', 'Jimis Burger',
       'Shobhaa Only Veg', 'One By Two', 'Go Biryan', 'Meal Bowl',
       'The Matka Biryani', 'Chote Nawab',
       "Mealful Rolls - India's Biggest Rolls",
       'Blue Tokai Coffee Roasters', 'Mainland China',
       'Flavours Of China', 'Slyce Pizza', 'Francesco\x92s Pizzeria',
       'Food Adda', 'Delhi Zaika', 'Raj Restaurant', 'Ovenfresh',
       'Aromas Cafe & Bistro', 'Casa Blanca', 'Dimsum Momo Express',
       "Juno's Pizza - Baking Fresh Since 1974",
       'Winners Pizza - Fresh Dough', 'HRX by EatFit', 'Hundo Pizza',
       "Hello Burger's", 'New Pankaj - Sandwich & Pani Puri', 'Wowfillss',
       'Chitale Xpress', 'Tossin Pizza', 'Speak Burgers by Vicky Ratnani',
       'Italian Bay', 'Gokul Refreshment', 'Naadbramha Idli',
       'SLAY Coffee', 'Mughlai Affair',
       'LeanCrust Pizza - ThinCrust Experts', 'Boojee Cafe', 'Art Of Dum',
       'Annamaya', 'Apoorva Delicacies', 'Potoba',
       'Sahara Family Restaurant', 'Momo Guy', 'The Fatty Bao',
       'Jhakas Family Restaurant', 'Fuel Up', 'Nino Burgers',
       'Firangi Bake', 'Food Darzee', 'Haka', 'Dindigul Veetu Kalyanam',
       'Anjappar', 'Mathsya', 'Salem RR Biriyani Unavagam', 'Al Faham',
       'Madurai Sri Thevar Hotel', 'Babal Da Punjabi Dabha',
       'Liza Restaurant', 'Ambaram Fast Food', 'Hotel Sennthur',
       'Taj Mughalai', "Reena Paul's Kitchen", 'Basheer Bai Biriyani',
       'Riyas Biriyani', 'Madurai Pandian Mess', 'Ibrahim Biriyani',
       'Buhari Vintage Hotel', 'Savoury Sea Shell',
       'Bismillah Briyani & Fast Foods', "Agarwal's Desi Khana Khazana",
       'Khalids Biriyani', 'Meat And Eat', 'Adhiya Beef Biriyani',
       'Junior Kuppanna', 'WOW! China', 'The Old Mirchi Biryani',
       'Ponnusamy Hotel', 'Shero Home Food - Chettinad',
       'Potful - Claypot Biryanis', 'A1 Ambur Briyani & Kababs',
       'Navrang Restaurant', 'Chicking', "AB's - Absolute Barbecues",
       'Little India', 'Little Hut', 'Zam Zam Briyani',
       'Shree Konar Vilas', "Writer's Cafe", 'Thanjai Veeraswamy',
       'Hotel Paramount', "Sam's Pork And Beef", 'Grill A Delics',
       'BurgerMan', 'The Chef Company', 'Five Star Chicken', 'Samco',
       'EatFit', 'Courtallam Border Rahmath Kadai', 'Cafe Amin',
       'BBQ Master', 'The High Joint', 'Great Indian Khichdi by EatFit',
       'Mr. Burger', "Jango'z", 'The Kati Roll Shop', 'Little Italy',
       'Eating Circles', 'Delhi Dhaba', 'Shawarma Kings', 'Nxtdoor',
       'Wangs Kitchen', 'Al Baik', 'Armaani Biryani', 'Tower Burger',
       'Go Grill', 'Toscano', 'Gusto Pizza', 'Kunafa House',
       "Lina's Brickoven Newyork Pizzeria", 'Ferrara Pizzeria',
       'The Burger Cafe', 'Kim Ling Chinese Restaurant',
       'T Shop - Tea, Snacks & More',
       'Tibet Momo - World Class Pan Asian Cuisine',
       'Chidambaram New Moorthy Cafe', 'KMS Hakkim Kalyana Biriyani',
       'Keifer', 'Taste Of Turkey', 'Oyalo Pizza',
       'NOTO - Healthy Ice Cream', 'Burger - Since 1989',
       'Imperial Bakery - Since 1955', 'Garden Vada Pav Centre',
       'Supreme Sandwich Corner', 'MH 12 Pav Bhaji', 'Pokket Cafe',
       'MOJO Pizza - 2X Toppings', 'Pizza Bites', 'KGN Xprs', "Wendy's",
       'Sandwich Express', 'The Pizza Box', 'Monginis', 'RK Pure Veg',
       'Roll Point', 'Marrakesh', 'New Bombay Sandwich Burger & Pizza',
       'Chill Out', 'Fried Chicken Destination', 'Hyderabadi Laziz',
       "Mother's Kitchen", 'Blue Nile', 'Bikkgane Biryani', 'Roopali Veg',
       'Burgerino', 'The Chinese Wok', 'Big Bowl', 'Sudama Bhel',
       'Best Belgian Waffle', 'NH1 Bowls - Highway To North', 'Sukanta',
       'Cream Craver', 'Jai Bhavani Snacks Center', 'Biggies Burger',
       'Karachi Sweet Mart', 'Saparito Pizza', "Big Daddy's",
       'Kannu Ki Chai', 'Chaayos Chai+Snacks=Relax', 'George Restaurant',
       'Piazza Pizza By Little Italy', "Bedi's Naan House",
       "Reddy's Fast Food", 'Choice Only Veg', 'King Of Burger',
       'Third Wave Coffee', 'Keventers - Milkshakes & Desserts',
       'Copper Chocs', 'Barista Coffee', 'Rawat Mishthan Bhandar',
       'RollsKing', 'The Pizza Unlimited', 'Kanha', 'Agarwal Caterers',
       'Unlimited Pizza & Fast Food Corner', 'Pizza Unlimited',
       "Chawla's Restaurant", 'Harishankar Veg Restro', "Pizza Baker's",
       'Sodhani Sweets Pvt. Ltd.', 'Sodhani Sweets And Namkeen',
       'Firewood Pizza', 'The Busy Beans', 'Kanji', 'The Pizza Station',
       'Brown Sugar', 'RJ Chai Wala', 'St. Louis Pizza',
       'The Waffle Bite', 'FPF  Coffee Wale Bhaiya', 'Punjabi Tadka',
       'Hil Pizza', 'Burger Shack', 'Ohh Taco', 'JBT Jaipur Burger Truck',
       'Victorian Bakery', 'The Yellow House - The Robot Restaurant',
       'Pizza Bar', 'Sethi Bar-Be-Que', 'Ganesh Bhojnalaya',
       'Vaishnav Dhaba', 'Tipsy Restaurant', 'Game Of Spices',
       'Swat Pizza', 'Bell Pepper Pizza', 'Just A Sec',
       'Burger Singh - Big Punjabi Burgers', 'Tan-Sukh By Kanha',
       'FPF Coffee Wale Bhaiya', 'Pizza And Burger King',
       'Sardaar Ji Chicken Co.', 'Choudhary Dhaba', 'Talk Of The Town',
       'Burger Lane', 'Dip N Bite', 'Khandelwal Dhaba Purana Wala',
       'Marky Momos', 'Kingdoms Pizza', 'Pandit Pav Bhaji',
       'Swadesi Station', 'JMD Bakery & Fast Food',
       'Ghungroo Seth Vada Pav Company', "Goofy's Pizza",
       'Laziz Chicken Food Restaurant', 'Roop Basant Pavitra Bhojnalaya',
       'Basant Dhaba', 'Jal Mahal Ice Cream Parlour', 'Balaji Fast Food',
       'Amma Ki Rasoi', 'U & Me Soya Chaap', 'Sai Chaap Soya',
       'Flavorsome Feasts', 'The Messy Door', 'Burgs & Fries', 'Cake Hut',
       'Shofu - The Momo Man', 'Shri Shyam Bhature Wala', 'Andewalaz',
       'Friedisthan', 'Mini Punjabi',
       'Unlimited Pizza and Fast Food Corner', "Chops 'N' Woks",
       'Captain Chick', 'Tapri Pratham', 'Arham', 'The Momoz Hub',
       'RR62 - Cafe & Kitchen', 'Al Taza', 'Cafe 17', 'Haji Ebrahim',
       'Thaal Kitchen', 'Arabian Dreams', 'Juicy', 'Bektash Turkishcafe',
       'Big Fat Momo', 'Empire Plaza', 'Falooda Nation',
       'Ceylon Bake House', 'Burger Spot',
       'Salkara Xpress By Paragon Group', 'Gokul Oottupura', 'Pitaworks',
       "Paputty's Valsa Cafe", 'Shawarma Daddy', 'Jugos',
       'Nellikka Restaurant', 'Dindigul Thalappakatti',
       'Buhari Special Juice', 'Baskin Robbins - Ice Cream Desserts',
       'Hotel Topform', 'Kunafa World', 'CEE YEM Bakers',
       'Nellikka Cloud Kitchen', 'Madheena Fried Chicken',
       'Cafe Durbar AFC', 'Cups & Cones', 'Burgeria',
       'Sijis Pizza Street', 'Beyondburg Inc', '12 To 12 BBQ',
       'Donut Factory', 'Pai Brothers 36 Varities Of Dosa',
       'Pai Brothers Fast Food', "Meera's Kitchen", 'Hoy Punjab', 'P60',
       'The Hearth Kitchen', 'Woodys Brook', 'Biriyani Bash',
       "Let's Eat Bakers", 'Grameen Kulfi', 'Rizo Resto', 'Firebirds',
       'Calicut Notebook', 'Rumaan Restaurant', 'Pizzaman',
       'Raw Squeezed', 'Manchatti Restaurant', 'Sukumar Food Court',
       'Porkeato De Portico', 'Quick Snacks', 'Tellicherry Kitchen',
       'Sheikh Shawarma', 'Dream Cutlets', 'Shap Food Restaurant',
       'Tea Shack', 'Pizza Ricotta', 'FFC', 'Golden Dragon',
       'Payasam Kada - Taste Trees', 'Meltyway', 'Ritz Classic',
       'Atlanta  Family Resto And Bar', 'NR - Navaratna Udupi Pure Veg',
       'Bar Malim', "Grillin' It", 'Namaste Chai',
       'Tasty Tiffin Food Service', 'Cafe Ave Maria', 'Cafe Cilantro',
       'TFC - The Food Club', 'The Royal Rucchik Restaurant', 'Mum Mai',
       'Atom-Bomb Quality Kitchen', 'Poi & Rolls Adda', 'Evoke',
       'Cafe Feed Me More', 'Biryani Hub', 'Patil Misal', 'Goyaan',
       "Bhosle's Food Court", 'Pakiza Restaurant', 'Cafe Central',
       'The Royal Ruchik', 'Cake Destination', 'Cafe Rasa',
       'Shivam Classic', 'Cafe Cup Of Joy', 'Joshi\x92s Masala Mantra',
       'Asian Bowls By Zahvi', 'Jubilee Restaurant',
       "Goa'rmet By The Tiffin Factory", "Domino's Pizza", 'Truffles',
       'KFC', 'Chinese Wok', 'Meghana Foods', 'A2B - Adyar Ananda Bhavan',
       'FreshMenu', 'Sangeetha Veg Restaurant - Gandhi Irwin Road',
       'Ambur Star Briyani', 'Real Arabia', 'Chowman', 'Arsalan',
       'Oudh 1590', "Kwality Wall's Frozen Dessert And Ice Cream Shop",
       'Baskin\xa0Robbins Happyness Shakes', 'Rominus Pizza And Burger',
       'Burger Farm', 'Thali and More', 'Roll Express',
       'Kwality Wall\x92s Frozen Dessert And Ice Cream Shop',
       'Laziz Pizza', 'Theobroma', "Aroma's Hyderabad House",
       'Rolls Mania', 'P. Bhagat Tarachand', "William John's Pizza",
       'Z K Fry Centre', 'HL Frankie', "The House Of Momo's",
       'Ghar Ka Khana by EatFit', 'Gordhan Thaal', 'Maharaja Thalis',
       'Fayrouz', 'Virasat - E - Curry', 'Jalaram', 'Cheers',
       'The Kebabish', 'Prithvi Hotel', "Day 'N' Night",
       'Shivam Bhojnalay', 'Hari Om Chole Puri', 'La Milano Pizzeria',
       'Nishat Restaurant', '1944 -The HOCCO Kitchen',
       'Alinea Restaurant & Banquet', 'The Grand Thakar', 'Khichdi Etc',
       'Dangee Dums', 'Hari Om Centre', 'Alpine Restaurant & Banquet',
       'New Bombay Biryani', 'Jay Bhavani Vadapav',
       'Shakti - The Sandwich Shop', 'A-One Bombay Biryani', 'Iscon Thal',
       'London Yard Pizza', 'Jassi De Parathe', 'Karnavati Dabeli',
       'Das Khaman', 'The Lio\x92 Pizza', 'Mumbaiya Misal & Vadapav',
       'Om Food Centre', 'Al Baik Fast Food', 'Farki', "Italio's Pizza",
       'MS Food', 'Purohit Restaurant', 'Puffizza', 'New Freeze Land',
       'Anand Bhajipav & Pulav Ankurwala',
       'Shree Marutinandan Kathiyawadi Restaurant', 'Karnavati Snacks',
       'Umiya Annpurna Kathiyawadi', 'Pizza Tune', "RP's Pizzeria",
       'Square Thali', 'Jay Shree Jalaram Parotha House', 'Gopi Bhog',
       'Momoman', 'Gajanand Pauva House', "Martino'z Pizza",
       "Sam's Pizza", 'Urban Khichdi', 'Vadilal - Scoop Shop',
       'Radhe Restaurants', 'PFZ', 'Bole To Vadapav',
       'Havmor Havfunn Ice Cream', 'Anjoy Latenight Meals',
       'Shree Mehfil', 'Jalaram Parotha House', 'The Mohalla',
       'Amritsar Punjab Paratha', 'Pizza Zone', 'The Hunger Box',
       'Living Bowls', 'Chickpet Donne Biryani House',
       'EasyBites by Empire', 'Beijing Bites', 'Andhra Gunpowder',
       'Behrouz Biryani', 'Aromas Of Biryani',
       'RNR Biryani - Taste Of 1953', 'Goli Vada Pav No. 1', 'Pizza@99',
       "Kataria's", 'Hotel N.G.T Non Veg', 'Goila Butter Chicken',
       'Puliyogare Point', 'Hari Super Sandwich', 'Shanmukha',
       'Rolls On Wheels', 'Donne Biryani House',
       'Karnataka Biryani Point', 'Meghduth Biryanis', 'Bucket Biryani',
       'GOPIZZA', 'Krispy Kreme', 'Chaat Street', 'Paratha Envy',
       'Sri Udupi Food Hub', 'Savi Sagar', 'Donne Biriyani Mane',
       'Roti Ghar', 'Pathaan Sir', 'Rajdhani', 'Ande Ka Funda',
       'Nandini Deluxe', 'Hotel Navayuga', 'Lulu Hypermarket',
       'Sandwich Guru', 'Hotel Karavali Food Point', 'Gopaljee Cafe',
       'Daily Sushi', 'Thalairaj Biryani', 'Nisarga', 'Razakhiya Hotel',
       '99 Variety Dosa & Pav Bhaji', 'Tapri By The Corner',
       'Texas Burgers', 'TKS Iyengars', 'Crispy Studio', 'Lassi N Cafe',
       'HSR High Street', 'IBC (Indian Biryani Company)', 'Just Cakes',
       '7 Plates', 'Magnolia Bakery', "Mother's Meal", 'Paratha Club',
       'Iyer Mess', 'Marwadi Chaat & Tiffin Services',
       'Kolkata Famous Kati Roll', 'Brik Oven', 'Keventers Ice Cream',
       'Chung Fa Restaurant', 'Wat-a-Burger! - India ka Burger',
       'Dastarkhwan', 'Pizza Cave', 'The American Pizza', 'The Oven',
       'Old Al - Baik', 'The Hazelnut Factory', 'Pizza Wizza',
       'Lalla Biryani - Since 1985', 'D Pizza Club', 'Mr. Brown - Danbro',
       'Pizzatarian', 'The Kalika Hut', 'Sharma Chai', 'Hot Pizza Ace',
       'Madhurima Veg', 'Grandson Of Tunday Kababi', 'Vadilal Ice Creams',
       'Pizza Pool', 'Pizza Potter', 'Pizza Pie',
       'Muradabadi Chicken Biryani', "LA'Pizza Club", 'Kuduk Chicken',
       'Craving Bites', 'Pawan Sweet & Bhojnalay',
       'Hotel Lazeez Al Darbar', 'Nukkad Cafe',
       'The Diamond Pizza & Chinese Point', 'Zeeshan Biryani Corner',
       'Mishra Bhojanalaya', 'Richi Rich', 'Goli Vadapav No.1',
       'Pizzaport & Cafe', 'Alibaba', 'Neelkanth Sweets',
       'Sharma Ji Ki Chai', 'Al Baik Xpress', 'Radhey Lal Sweets',
       "Rattilal's - Sitapur Road", 'Billu Tandooria', 'The Dastarkhan',
       'Tuday Kebabi', 'Spice Village',
       "Bombay Natural's Pizza & Soya Chaap", 'Home Town Pizza',
       'Balle Balle Delhi Wale Soya Chaap Zone', 'PVR Café',
       'Deva Food Mart', 'The Garam Chulha', 'Maharaja Restaurant',
       'Roasties', 'Pizza Pandey', 'Royalz Pepper', 'Farzi Cafe',
       'Nazeer Foods', 'Baap Of Rolls', 'Paparizza - Woodfired Pizzas',
       'Big Smokin Burgers', 'Burger Xpress', 'Alkakori',
       'ICP Italian Crust Pizza', 'Anju Sweets', 'Apni Rasoi Int',
       'Hira Sweets', 'Pizza Studio', 'Kings Kulfi',
       'Prasuma Momo Kitchen', "Good Flippin' Burgers",
       "Chili's Grill & Bar", 'Delhi Darbar Dhaba', 'Diggin',
       'Tite Da Dhaba', 'Hashtag Foods', 'Oven Day Pizza', 'If Pizza',
       'Shiraz Golden Restaurant', 'Grab Feast', 'Lazeez Biryani',
       'Rosy Roti', 'Royal Indian Hotel  - Since 1905',
       'The Burping Panda', 'Zam Zam Restaurant', 'Rang De Basanti Dhaba',
       'Edabba', 'Hatari', 'Mitra Cafe', 'Mama Mia!', 'Kathi Junction',
       'Raasta Cafe', 'Sher-E-Punjab', 'Momo I Am', 'Kreamz',
       'New Paul Dhaba Veggie Hub', 'Shawarma Nation', 'Veggie Corner',
       "Goutam's", 'Fried Chicken Wala',
       'Balaram Mullick & Radharaman Mullick Sweets', 'Roy Pizza House',
       'The Biryani Inc.', 'Rollick', "Sip 'N' Bite's", 'Dreams Cafe',
       'Pizza Wala', 'HFC', 'Taj Biryani', 'Mezban', 'Eagle Bites Pizza',
       'I Love Haldiram', 'WFC - Wow Fried Chicken',
       'Super Star Hazi Biryani', 'Saima Restaurant', 'Raffs F9',
       'Khana Khazana', 'Roy Dhaba', 'Noodle King', 'Golden Joy',
       'Burger In Law', 'Tea Junction', 'The Bahubelly', 'Safe House',
       'Peaberrys', 'Axis Juice', 'Sikkim Jojo', 'Manju Mamta Restaurant',
       'Hotel Hyderabadi', 'Pizza Olive', 'Moti Mahal', 'Sandwich Jn.',
       'Chicago Pizza', 'Momo Magic Cafe', "Mario's", 'Pizza@89',
       'Creams N Caffeine', 'Veggiies', 'Pizza @90', 'Urban Biryani',
       'Jalaram Sweets And Namkeen', 'Galaxy Food Centre', 'Pavdos Cafe',
       'Uno Dos Tres', "Kikki's Cafe",
       'Hot Chemistry- Indian Heritage Hotel', "Ustaad's Kitchen",
       'Ashifa Laziz Biryani', 'Starbucks Coffee',
       'Goli Rolls And Vada Pav', 'Hot 100', 'Confusion Box',
       'Samriddhi Thali', "CA's Kitchen", 'Pure Momos', 'Bunk Class',
       'Chapter One', 'Cafe 36', 'Wafflez', 'Sandwich Junction',
       'Just Chaska', 'Tandoor -3 Family Dhaba', "Chef's Kitchen",
       'Iconic Cafe', 'Binge Box', 'Chai Govindam', 'Xero Degrees',
       'KGN Chicken Corner & Biryani Center', 'Pohewala',
       'The Breakfast Cafe', 'Dakshin Swaad', 'Ariena Boutique Hotel'],
      dtype=object)

In [172]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123657 entries, 0 to 123656
Data columns (total 12 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Restaurant Name  123657 non-null  object
 1   Dining Rating    123657 non-null  float64
 2   Delivery Rating  123657 non-null  float64
 3   Dining Votes     123657 non-null  int64
 4   Delivery Votes   123657 non-null  int64
 5   Cuisine          123657 non-null  object
 6   Place Name       123657 non-null  object
 7   City             123657 non-null  object
 8   Item Name        123657 non-null  object
 9   Best Seller      123657 non-null  object
 10  Votes            123657 non-null  int64
 11  Prices           123657 non-null  float64
dtypes: float64(3), int64(3), object(6)
memory usage: 11.3+ MB

In [173]:
subset4 =x.iloc[:,[0]]

In [174]:
subset4

              Restaurant Name
0                  Doner King
1                  Doner King
2                  Doner King
3                  Doner King
4                  Doner King
...                       ...
123652  Ariena Boutique Hotel
123653  Ariena Boutique Hotel
123654  Ariena Boutique Hotel
123655  Ariena Boutique Hotel
123656  Ariena Boutique Hotel

[123657 rows x 1 columns]

#encoding

In [175]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [176]:
a_encoder=le.fit_transform(subset4)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [177]:
a_encoder

array([207, 207, 207, ...,  51,  51,  51])

In [178]:
x['Restaurant Name']=le.fit_transform(x['Restaurant Name'])

In [179]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,207,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,207,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,207,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,BESTSELLER,39,189.0
3,207,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,207,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,51,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Reshmi Kebab,BESTSELLER,0,525.0
123653,51,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Large Tikka,BESTSELLER,0,525.0
123654,51,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Chukandri Tikka,BESTSELLER,0,525.0
123655,51,3.9,4.2,13,523,Pizza,Purena,Raipur,Murgh Golden Kebab,BESTSELLER,0,525.0
123656,51,3.9,4.2,13,523,Pizza,Purena,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [180]:
x['Place Name'].unique()

array(['Malakpet', 'The Next Galleria Mall', 'Himayath Nagar',
       'Nallakunta', 'Tolichowki', 'Charminar', 'Taj Mahal Hotel',
       'Kothapet', 'Abids', 'Mehdipatnam', 'Yousufguda', 'Dilsukhnagar',
       'Koti', 'Falaknuma', 'Begum Bazaar', 'Chandrayanagutta',
       'MPM Mall', 'RTC X roads', 'Saroor Nagar', 'Ghansi Bazaar',
       'Lakdikapul', 'Banjara Hills', 'Basheer Bagh', 'Kacheguda',
       'Charminar Area', 'Attapur', 'Nampally', 'Khairatabad',
       'Musheerabad', 'Boiguda', 'Narayanguda', 'Masab Tank', 'Meerpet',
       'Langer Houz', 'Amberpet', 'Somajiguda', '12th Square Building',
       'Matunga East', 'Lower Parel', 'Wadala', 'Worli', 'Dadar East',
       'Khar', 'Sion', 'Chembur', 'Dadar Shivaji Park', 'Dadar West',
       'Pali Hill', 'Parel', 'Prabhadevi', 'Mahalaxmi', 'Mahim',
       'Linking Road', 'Byculla', 'Kurla', 'Bandra Kurla Complex',
       'Hill Road', 'Carter Road', 'Egmore', 'Parrys', 'Triplicane',
       'Vepery', 'Anna Salai', 'Purasavakkam', 'Anna Nagar West',
       'Royapettah', 'Kilpauk', 'Thousand Lights', 'Kolathur', 'T. Nagar',
       'Nungambakkam', 'Aminijikarai', 'Alwarpet', 'Choolaimedu',
       'Anna Nagar East', 'Washermenpet', 'Perambur', 'Royapuram',
       'Gopalapuram', 'Arumbakkam', 'Mylapore', 'Kora Food Street',
       'George Town', 'Kothrud', 'Koregaon Park', 'East Street',
       'Camp Area', 'Budhwar Peth', 'Rasta Peth', 'Karve Nagar',
       'Bund Garden Road', 'Wadgaon Sheri', 'Aundh', 'Law College Road',
       'Senapati Bapat Road', 'Sadashiv Peth', 'Vishrantwadi',
       'Dhankawadi', 'FC Road', 'Bibvewadi', 'Kondhwa',
       'Kumar Pacific Mall', 'Yerawada', 'Erandwane', 'Dhole Patil Road',
       'Deccan Gymkhana', 'Katraj', 'Salunkhe Vihar Road', 'Fatima Nagar',
       'Sinhgad Road', 'The Pavillion', 'MG Road', 'C Scheme',
       'Sindhi Camp', 'Raja Park', 'Pink City', 'Shastri Nagar',
       'Bapu Nagar', 'Gopalpura', 'Jhotwara', 'Axis Mall', 'Bais Godam',
       'Malviya Nagar', 'Vaishali Nagar', 'Jawahar Nagar', 'Sodala',
       'Bani Park', 'Lal Kothi', 'Vidhyadhar Nagar', 'Mansarovar',
       'Brahmpuri', 'Khatipura Road', 'MI Road', 'Tonk Phatak',
       'Sikar Road', 'Amer Road', 'Durgapura', 'Crystal Palm Mall',
       'Gopalbari', 'Ajmer Highway', 'Masala Chowk', 'Kaloor',
       'Ravipuram', 'Kadavanthra', 'Thopumpady', 'Marad', 'Kacheripady',
       'Chittoor Road', 'Marine Drive', 'GCDA Shopping Complex',
       'Vyttila', 'Pallimukku', 'Edappally', 'Palluruthy',
       'Panampilly Nagar', 'Palarivattom', 'Centre Square Mall',
       'Elamakkara', 'Ernakulam City', 'Tripunithura', 'Vennala',
       'Fort Kochi', 'Mattancherry', 'Mall De Goa', 'Porvorim',
       'Penha de Franca', 'Panaji', 'Bardez', 'Candolim', 'Saligao',
       'St. Marks Road', 'Shanti Nagar', 'Commercial Street',
       'Brigade Road', 'Basavanagudi', 'Mantri Square', 'Cunningham Road',
       'Frazer Town', 'Malleshwaram', 'Wilson Garden', 'Church Street',
       'Domlur', 'Residency Road', 'Garuda Mall', 'Richmond Road',
       'Park Town', 'Sealdah Area', 'Entally', 'Hatibagan',
       'Park Street Area', 'Sector 1', 'New Market Area', 'Esplanade',
       'College Street', 'Kankurgachi', 'Theatre Road', 'Girish Park',
       'Pink Square Mall', 'Star Mall', 'Matunga West', 'Shaniwar Peth',
       'R Deccan Mall', 'Shukrawar Peth', 'JM Road', 'Mani Nagar',
       'Navrangpura', 'Bhadra', 'Gulbai Tekra', 'Satellite', 'Gurukul',
       'Prahlad Nagar', 'Memnagar', 'Kalupur', 'C G Road', 'Kankaria',
       'Ellis Bridge', 'Ambavadi', 'Paldi', 'Vastrapur', 'Shahpur',
       'Shahibagh', 'Astodia', 'Lal Darwaja', 'Ashram Road', 'Naranpura',
       'Shivalik Yash', 'Isanpur', 'Bapunagar', 'Subhash Bridge', 'Sola',
       'Bodakdev', 'Koramangala 7th Block', 'Jayanagar', 'Seshadripuram',
       'Kammanahalli', 'Rajajinagar', 'BTM', 'Vijay Nagar',
       'Koramangala 6th Block', 'JP Nagar', 'Sanjay Nagar', 'Orion East',
       'Koramangala 4th Block', 'Lido Mall', 'Majestic', 'Lavelle Road',
       'Indiranagar', 'Banaswadi', 'Basaveshwara Nagar', 'HBR Layout',
       'Koramangala 5th Block', 'Thippasandra', 'HSR', 'CV Raman Nagar',
       'New BEL Road', 'Nagawara', 'Gomti Nagar', 'Mahanagar',
       'Hazratganj', 'Kaiserbagh', 'Chowk', 'Indira Nagar',
       'Nirala Nagar', 'Lalbagh', 'Jopling Road', 'Rajajipuram',
       'Aliganj', 'Sahara Ganj Mall', 'Jankipuram', 'Khurram Nagar',
       'Triveni Nagar', 'Charbagh', 'Connaught Place', 'Cyber Hub',
       'Lajpat Nagar 2', 'Laxmi Nagar', 'Delhi University-GTB Nagar',
       'Mukherjee Nagar', 'Geeta Colony', 'Inderlok', 'Pandav Nagar',
       'Rajinder Nagar', 'Karol Bagh', 'Greater Kailash 1 (GK1)',
       'Gole Market', 'Rajouri Garden', 'Kamla Nagar', 'West Patel Nagar',
       'Topsia', 'Bara Bazar', 'Park Circus Area', 'Bow Bazar',
       'Shobha Bazar', 'Lake Town', 'Dobson Road', 'Beliaghata',
       'City Centre 1', 'Maniktala', 'Liluah', 'Shibpur', 'Sector 4',
       'Kasba', 'Shalimar', 'Das Naagar', 'Wellesley',
       'Ruby Hospital Area', 'Dum Dum', 'Chowringhee', 'Ultadanga',
       'Picnic Garden', 'Tangra', 'Devendra Nagar', 'Civil Lines',
       'Moudhapara', 'Mahaveer Nagar', 'Samta Colony', 'Mowa',
       'Tatibandh', 'Tikrapara', 'Kota', 'Shankar Nagar', 'Amanaka',
       'Purena', 'Govind Nagar'], dtype=object)

In [181]:
x['Place Name'] = le.fit_transform(x['Place Name'])

In [182]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,207,3.9,4.2,39,0,Fast Food,184,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,207,3.9,4.2,39,0,Fast Food,184,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,207,3.9,4.2,39,0,Fast Food,184,Hyderabad,Chicken Tandoori Salad,BESTSELLER,39,189.0
3,207,3.9,4.2,39,0,Fast Food,184,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,207,3.9,4.2,39,0,Fast Food,184,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,51,3.9,4.2,13,523,Pizza,240,Raipur,Murgh Reshmi Kebab,BESTSELLER,0,525.0
123653,51,3.9,4.2,13,523,Pizza,240,Raipur,Murgh Large Tikka,BESTSELLER,0,525.0
123654,51,3.9,4.2,13,523,Pizza,240,Raipur,Murgh Chukandri Tikka,BESTSELLER,0,525.0
123655,51,3.9,4.2,13,523,Pizza,240,Raipur,Murgh Golden Kebab,BESTSELLER,0,525.0
123656,51,3.9,4.2,13,523,Pizza,240,Raipur,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [183]:
x['City'].unique

<bound method Series.unique of 0          Hyderabad
1          Hyderabad
2          Hyderabad
3          Hyderabad
4          Hyderabad
             ...
123652        Raipur
123653        Raipur
123654        Raipur
123655        Raipur
123656        Raipur
Name: City, Length: 123657, dtype: object>

In [184]:
x['City'] = le.fit_transform(x['City'])

In [185]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,207,3.9,4.2,39,0,Fast Food,184,5,Platter Kebab Combo,BESTSELLER,84,249.0
1,207,3.9,4.2,39,0,Fast Food,184,5,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,207,3.9,4.2,39,0,Fast Food,184,5,Chicken Tandoori Salad,BESTSELLER,39,189.0
3,207,3.9,4.2,39,0,Fast Food,184,5,Chicken BBQ Salad,BESTSELLER,43,189.0
4,207,3.9,4.2,39,0,Fast Food,184,5,Special Doner Wrap Combo,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,51,3.9,4.2,13,523,Pizza,240,15,Murgh Reshmi Kebab,BESTSELLER,0,525.0
123653,51,3.9,4.2,13,523,Pizza,240,15,Murgh Large Tikka,BESTSELLER,0,525.0
123654,51,3.9,4.2,13,523,Pizza,240,15,Murgh Chukandri Tikka,BESTSELLER,0,525.0
123655,51,3.9,4.2,13,523,Pizza,240,15,Murgh Golden Kebab,BESTSELLER,0,525.0
123656,51,3.9,4.2,13,523,Pizza,240,15,Gosht Gilawat Chop,BESTSELLER,0,595.0

In [186]:
x['Item Name'] = le.fit_transform(x['Item Name'])

In [187]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,207,3.9,4.2,39,0,Fast Food,184,5,41530,BESTSELLER,84,249.0
1,207,3.9,4.2,39,0,Fast Food,184,5,12242,BESTSELLER,45,129.0
2,207,3.9,4.2,39,0,Fast Food,184,5,12837,BESTSELLER,39,189.0
3,207,3.9,4.2,39,0,Fast Food,184,5,9249,BESTSELLER,43,189.0
4,207,3.9,4.2,39,0,Fast Food,184,5,46959,MUST TRY,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,51,3.9,4.2,13,523,Pizza,240,15,33734,BESTSELLER,0,525.0
123653,51,3.9,4.2,13,523,Pizza,240,15,33691,BESTSELLER,0,525.0
123654,51,3.9,4.2,13,523,Pizza,240,15,33643,BESTSELLER,0,525.0
123655,51,3.9,4.2,13,523,Pizza,240,15,33654,BESTSELLER,0,525.0
123656,51,3.9,4.2,13,523,Pizza,240,15,23525,BESTSELLER,0,595.0

In [188]:
x['Best Seller'].unique

<bound method Series.unique of 0         BESTSELLER
1         BESTSELLER
2         BESTSELLER
3         BESTSELLER
4           MUST TRY
             ...
123652    BESTSELLER
123653    BESTSELLER
123654    BESTSELLER
123655    BESTSELLER
123656    BESTSELLER
Name: Best Seller, Length: 123657, dtype: object>

In [189]:
x['Best Seller'] = le.fit_transform(x['Best Seller'])

In [145]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,207,3.9,4.2,39,0,Fast Food,184,5,41530,0,84,249.0
1,207,3.9,4.2,39,0,Fast Food,184,5,12242,0,45,129.0
2,207,3.9,4.2,39,0,Fast Food,184,5,12837,0,39,189.0
3,207,3.9,4.2,39,0,Fast Food,184,5,9249,0,43,189.0
4,207,3.9,4.2,39,0,Fast Food,184,5,46959,6,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,51,3.9,4.2,13,523,Pizza,240,15,33734,0,0,525.0
123653,51,3.9,4.2,13,523,Pizza,240,15,33691,0,0,525.0
123654,51,3.9,4.2,13,523,Pizza,240,15,33643,0,0,525.0
123655,51,3.9,4.2,13,523,Pizza,240,15,33654,0,0,525.0
123656,51,3.9,4.2,13,523,Pizza,240,15,23525,0,0,595.0

In [200]:
x['Cuisine '] = le.fit_transform(x['Cuisine '])

In [202]:
x

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,207,3.9,4.2,39,0,12,184,5,41530,0,84,249.0
1,207,3.9,4.2,39,0,12,184,5,12242,0,45,129.0
2,207,3.9,4.2,39,0,12,184,5,12837,0,39,189.0
3,207,3.9,4.2,39,0,12,184,5,9249,0,43,189.0
4,207,3.9,4.2,39,0,12,184,5,46959,6,31,205.0
...,...,...,...,...,...,...,...,...,...,...,...,...
123652,51,3.9,4.2,13,523,31,240,15,33734,0,0,525.0
123653,51,3.9,4.2,13,523,31,240,15,33691,0,0,525.0
123654,51,3.9,4.2,13,523,31,240,15,33643,0,0,525.0
123655,51,3.9,4.2,13,523,31,240,15,33654,0,0,525.0
123656,51,3.9,4.2,13,523,31,240,15,23525,0,0,595.0

In [203]:
shallow1 = x.copy()

In [204]:
data1 = shallow1.values

In [205]:
data1

array([[207. ,   3.9,   4.2, ...,   0. ,  84. , 249. ],
       [207. ,   3.9,   4.2, ...,   0. ,  45. , 129. ],
       [207. ,   3.9,   4.2, ...,   0. ,  39. , 189. ],
       ...,
       [ 51. ,   3.9,   4.2, ...,   0. ,   0. , 525. ],
       [ 51. ,   3.9,   4.2, ...,   0. ,   0. , 525. ],
       [ 51. ,   3.9,   4.2, ...,   0. ,   0. , 595. ]])

NORMALIZATION x norm = x - x min/x max- x min 0 to 1

In [197]:
from sklearn import preprocessing
from sklearn.preprocessing import Normalizer

2)L1 NORMALIZATION / LEAST ABSOLUTE DEVIATION

In [207]:
data_norm = Normalizer(norm ='l1').fit(data1)
data_norm1 = data_norm.transform(data1)
print(data_norm1)

[[4.89152396e-03 9.21591470e-05 9.92483122e-05 ... 0.00000000e+00
  1.98496624e-03 5.88400708e-03]
 [1.60825415e-02 3.03004405e-04 3.26312436e-04 ... 0.00000000e+00
  3.49620468e-03 1.00224534e-02]
 [1.53105376e-02 2.88459405e-04 3.10648590e-04 ... 0.00000000e+00
  2.88459405e-03 1.39791865e-02]
 ...
 [1.45510156e-03 1.11272472e-04 1.19831893e-04 ... 0.00000000e+00
  0.00000000e+00 1.49789866e-02]
 [1.45464502e-03 1.11237561e-04 1.19794296e-04 ... 0.00000000e+00
  0.00000000e+00 1.49742870e-02]
 [2.03991024e-03 1.55993136e-04 1.67992608e-04 ... 0.00000000e+00
  0.00000000e+00 2.37989528e-02]]

In [208]:
data_norm = Normalizer(norm='l2').fit(data1)
data_norm2 = data_norm.transform(data1)
print(data_norm2)

[[4.98413557e-03 9.39040035e-05 1.01127388e-04 ... 0.00000000e+00
  2.02254777e-03 5.99540945e-03]
 [1.69035271e-02 3.18472249e-04 3.42970114e-04 ... 0.00000000e+00
  3.67467979e-03 1.05340821e-02]
 [1.61196065e-02 3.03702731e-04 3.27064480e-04 ... 0.00000000e+00
  3.03702731e-03 1.47179016e-02]
 ...
 [1.51550830e-03 1.15891811e-04 1.24806566e-04 ... 0.00000000e+00
  0.00000000e+00 1.56008208e-02]
 [1.51501322e-03 1.15853952e-04 1.24765794e-04 ... 0.00000000e+00
  0.00000000e+00 1.55957243e-02]
 [2.16655797e-03 1.65677962e-04 1.78422421e-04 ... 0.00000000e+00
  0.00000000e+00 2.52765096e-02]]

In [209]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

In [210]:
data_std = StandardScaler()

In [211]:
std = data_std.fit_transform(data1)
std

array([[-0.85135924,  0.23763904,  0.96075548, ..., -0.28149764,
         0.47377323,  0.03952499],
       [-0.85135924,  0.23763904,  0.96075548, ..., -0.28149764,
         0.16235994, -0.58278503],
       [-0.85135924,  0.23763904,  0.96075548, ..., -0.28149764,
         0.1144502 , -0.27163002],
       ...,
       [-1.50526447,  0.23763904,  0.96075548, ..., -0.28149764,
        -0.19696309,  1.47083804],
       [-1.50526447,  0.23763904,  0.96075548, ..., -0.28149764,
        -0.19696309,  1.47083804],
       [-1.50526447,  0.23763904,  0.96075548, ..., -0.28149764,
        -0.19696309,  1.83385222]])

In [212]:
data_norm3 = preprocessing.normalize(data1)

In [213]:
data_norm3

array([[4.98413557e-03, 9.39040035e-05, 1.01127388e-04, ...,
        0.00000000e+00, 2.02254777e-03, 5.99540945e-03],
       [1.69035271e-02, 3.18472249e-04, 3.42970114e-04, ...,
        0.00000000e+00, 3.67467979e-03, 1.05340821e-02],
       [1.61196065e-02, 3.03702731e-04, 3.27064480e-04, ...,
        0.00000000e+00, 3.03702731e-03, 1.47179016e-02],
       ...,
       [1.51550830e-03, 1.15891811e-04, 1.24806566e-04, ...,
        0.00000000e+00, 0.00000000e+00, 1.56008208e-02],
       [1.51501322e-03, 1.15853952e-04, 1.24765794e-04, ...,
        0.00000000e+00, 0.00000000e+00, 1.55957243e-02],
       [2.16655797e-03, 1.65677962e-04, 1.78422421e-04, ...,
        0.00000000e+00, 0.00000000e+00, 2.52765096e-02]])

In [218]:
data_norm4 = preprocessing.scale(data1)

In [219]:
data_norm4

array([[-0.85135924,  0.23763904,  0.96075548, ..., -0.28149764,
         0.47377323,  0.03952499],
       [-0.85135924,  0.23763904,  0.96075548, ..., -0.28149764,
         0.16235994, -0.58278503],
       [-0.85135924,  0.23763904,  0.96075548, ..., -0.28149764,
         0.1144502 , -0.27163002],
       ...,
       [-1.50526447,  0.23763904,  0.96075548, ..., -0.28149764,
        -0.19696309,  1.47083804],
       [-1.50526447,  0.23763904,  0.96075548, ..., -0.28149764,
        -0.19696309,  1.47083804],
       [-1.50526447,  0.23763904,  0.96075548, ..., -0.28149764,
        -0.19696309,  1.83385222]])

In [220]:
data_norm5 = MinMaxScaler().fit_transform(data1)

In [221]:
data_norm5

array([[0.25090909, 0.60869565, 0.80952381, ..., 0.        , 0.00861538,
        0.0206312 ],
       [0.25090909, 0.60869565, 0.80952381, ..., 0.        , 0.00461538,
        0.01065038],
       [0.25090909, 0.60869565, 0.80952381, ..., 0.        , 0.004     ,
        0.01564079],
       ...,
       [0.06181818, 0.60869565, 0.80952381, ..., 0.        , 0.        ,
        0.04358711],
       [0.06181818, 0.60869565, 0.80952381, ..., 0.        , 0.        ,
        0.04358711],
       [0.06181818, 0.60869565, 0.80952381, ..., 0.        , 0.        ,
        0.04940926]])